services:
  vcs:
    image: gitlab/gitlab-ce:17.1.2-ce.0
    hostname: vcs
    restart: always
    container_name: vcs
    environment:
      TZ: Asia/Seoul
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://vcs.zzizily'
        nginx['redirect_http_to_https'] = false
        nginx['listen_port'] = 80
        nginx['listen_https']= false
        letsencrypt['enable'] = false
        gitlab_rails['time_zone'] = 'Asia/Seoul'
        gitlab_rails['gitlab_shell_ssh_port'] = '10022'
        gitlab_rails['smtp_enable'] = false
    networks:
      - zzizily
    ports:
      - 9002:80
      - 10022:22
      - 5050:5050
      - 8060:8060
    extra_hosts:
      - local.zzizily.com:127.0.0.1
    logging:
      options:
        max-size: 10m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - etc:/etc/gitlab
      - data:/var/opt/gitlab
networks:
  zzizily:
    external: true
volumes:
  data: null
  etc: null
