services:
  repo:
    image: sonatype/nexus3:latest
    container_name: repo
    hostname: repo
    restart: always
    environment:
      TZ: Asia/Seoul
    networks:
      - zzizily
    ports:
      - 9003:8081/tcp
    extra_hosts:
      - local.zzizily.com:127.0.0.1
    logging:
      options:
        max-size: 10m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/nexus-data
networks:
  zzizily:
    external: true
volumes:
  data: null
