services:
  uptime:
    image: louislam/uptime-kuma:1
    container_name: uptime
    hostname: uptime
    restart: unless-stopped
    networks:
      - zzizily
    ports:
      - 9009:3001
    extra_hosts:
      - local.zzizily.com:127.0.0.1
    logging:
      options:
        max-size: 10m
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/app/data
networks:
  zzizily:
    external: true
volumes:
  data: null
