services:
  docker:
    build: ./dind
    privileged: true
    container_name: docker
    hostname: docker
    restart: always
    environment:
      - TZ=Asia/Seoul
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - zzizily
    ports:
      - 42376:2376
    extra_hosts:
      - local.zzizily.com:127.0.0.1
    logging:
      options:
        max-size: 10m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - certs_client:/certs/client
      - data_docker:/var/jenkins_home
  ci:
    build: ./ci
    container_name: ci
    hostname: ci
    restart: always
    environment:
      TZ: Asia/Seoul
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    networks:
      - zzizily
    ports:
      - 9001:8080
      - 50000:50000
    extra_hosts:
      - local.zzizily.com:127.0.0.1
    logging:
      options:
        max-size: 10m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - certs_client:/certs/client:ro
      - data_ci:/var/jenkins_home
networks:
  zzizily:
    external: true
volumes:
  certs_client: null
  data_docker: null
  data_ci: null
