plugins:
- artifactId: ansible
  source:
    version: 307.va_1f3ef06575a_
- artifactId: ansicolor
  source:
    version: 1.0.4
- artifactId: ant
  source:
    version: 497.v94e7d9fffa_b_9
- artifactId: antisamy-markup-formatter
  source:
    version: 162.v0e6ec0fcfcf6
- artifactId: apache-httpcomponents-client-4-api
  source:
    version: 4.5.14-208.v438351942757
- artifactId: apache-httpcomponents-client-5-api
  source:
    version: 5.3.1-1.0
- artifactId: asm-api
  source:
    version: 9.7-33.v4d23ef79fcc8
- artifactId: authentication-tokens
  source:
    version: 1.113.v81215a_241826
- artifactId: aws-credentials
  source:
    version: 231.v08a_59f17d742
- artifactId: aws-java-sdk-ec2
  source:
    version: 1.12.730-457.v3403b_37d2170
- artifactId: aws-java-sdk-minimal
  source:
    version: 1.12.730-457.v3403b_37d2170
- artifactId: blueocean-bitbucket-pipeline
  source:
    version: 1.27.13
- artifactId: blueocean-commons
  source:
    version: 1.27.13
- artifactId: blueocean-config
  source:
    version: 1.27.13
- artifactId: blueocean-core-js
  source:
    version: 1.27.13
- artifactId: blueocean-dashboard
  source:
    version: 1.27.13
- artifactId: blueocean-display-url
  source:
    version: 2.4.2
- artifactId: blueocean-events
  source:
    version: 1.27.13
- artifactId: blueocean-git-pipeline
  source:
    version: 1.27.13
- artifactId: blueocean-github-pipeline
  source:
    version: 1.27.13
- artifactId: blueocean-i18n
  source:
    version: 1.27.13
- artifactId: blueocean-jwt
  source:
    version: 1.27.13
- artifactId: blueocean-personalization
  source:
    version: 1.27.13
- artifactId: blueocean-pipeline-api-impl
  source:
    version: 1.27.13
- artifactId: blueocean-pipeline-editor
  source:
    version: 1.27.13
- artifactId: blueocean-pipeline-scm-api
  source:
    version: 1.27.13
- artifactId: blueocean-rest-impl
  source:
    version: 1.27.13
- artifactId: blueocean-rest
  source:
    version: 1.27.13
- artifactId: blueocean-web
  source:
    version: 1.27.13
- artifactId: blueocean
  source:
    version: 1.27.13
- artifactId: bootstrap5-api
  source:
    version: 5.3.3-1
- artifactId: bouncycastle-api
  source:
    version: 2.30.1.78.1-233.vfdcdeb_0a_08a_a_
- artifactId: branch-api
  source:
    version: 2.1169.va_f810c56e895
- artifactId: build-timeout
  source:
    version: 1.32
- artifactId: build-timestamp
  source:
    version: 1.0.3
- artifactId: caffeine-api
  source:
    version: 3.1.8-133.v17b_1ff2e0599
- artifactId: checks-api
  source:
    version: 2.2.0
- artifactId: cloud-stats
  source:
    version: 336.v788e4055508b_
- artifactId: cloudbees-bitbucket-branch-source
  source:
    version: 886.v44cf5e4ecec5
- artifactId: cloudbees-folder
  source:
    version: 6.928.v7c780211d66e
- artifactId: command-launcher
  source:
    version: 107.v773860566e2e
- artifactId: commons-lang3-api
  source:
    version: 3.14.0-76.vda_5591261cfe
- artifactId: commons-text-api
  source:
    version: 1.12.0-119.v73ef73f2345d
- artifactId: config-file-provider
  source:
    version: 973.vb_a_80ecb_9a_4d0
- artifactId: configuration-as-code
  source:
    version: 1810.v9b_c30a_249a_4c
- artifactId: credentials-binding
  source:
    version: 677.vdc9d38cb_254d
- artifactId: credentials
  source:
    version: 1337.v60b_d7b_c7b_c9f
- artifactId: dark-theme
  source:
    version: 439.vdef09f81f85e
- artifactId: display-url-api
  source:
    version: 2.204.vf6fddd8a_8b_e9
- artifactId: docker-commons
  source:
    version: 439.va_3cb_0a_6a_fb_29
- artifactId: docker-java-api
  source:
    version: 3.3.6-90.ve7c5c7535ddd
- artifactId: docker-plugin
  source:
    version: 1.6.2
- artifactId: docker-workflow
  source:
    version: 580.vc0c340686b_54
- artifactId: durable-task
  source:
    version: 555.v6802fe0f0b_82
- artifactId: echarts-api
  source:
    version: 5.5.0-1
- artifactId: eddsa-api
  source:
    version: 0.3.0-4.v84c6f0f4969e
- artifactId: email-ext
  source:
    version: 1814.v404722f34263
- artifactId: favorite
  source:
    version: 2.208.v91d65b_7792a_c
- artifactId: font-awesome-api
  source:
    version: 6.5.2-1
- artifactId: git-client
  source:
    version: 4.7.0
- artifactId: git-parameter
  source:
    version: 0.9.19
- artifactId: git
  source:
    version: 5.2.2
- artifactId: github-api
  source:
    version: 1.318-461.v7a_c09c9fa_d63
- artifactId: github-branch-source
  source:
    version: 1789.v5b_0c0cea_18c3
- artifactId: github
  source:
    version: 1.39.0
- artifactId: gradle
  source:
    version: 2.12
- artifactId: groovy
  source:
    version: 457.v99900cb_85593
- artifactId: gson-api
  source:
    version: 2.11.0-41.v019fcf6125dc
- artifactId: h2-api
  source:
    version: 11.1.4.199-30.v1c64e772f3a_c
- artifactId: handy-uri-templates-2-api
  source:
    version: 2.1.8-30.v7e777411b_148
- artifactId: harbor
  source:
    version: 32.vc848ea_c101d6
- artifactId: htmlpublisher
  source:
    version: 1.34
- artifactId: instance-identity
  source:
    version: 185.v303dc7c645f9
- artifactId: ionicons-api
  source:
    version: 74.v93d5eb_813d5f
- artifactId: jackson2-api
  source:
    version: 2.17.0-379.v02de8ec9f64c
- artifactId: jakarta-activation-api
  source:
    version: 2.1.3-1
- artifactId: jakarta-mail-api
  source:
    version: 2.1.3-1
- artifactId: javax-activation-api
  source:
    version: 1.2.0-7
- artifactId: javax-mail-api
  source:
    version: 1.6.2-10
- artifactId: jaxb
  source:
    version: 2.3.9-1
- artifactId: jdk-tool
  source:
    version: 73.vddf737284550
- artifactId: jenkins-design-language
  source:
    version: 1.27.13
- artifactId: jjwt-api
  source:
    version: 0.11.5-112.ve82dfb_224b_a_d
- artifactId: joda-time-api
  source:
    version: 2.12.7-29.v5a_b_e3a_82269a_
- artifactId: jquery3-api
  source:
    version: 3.7.1-2
- artifactId: json-api
  source:
    version: 20240303-41.v94e11e6de726
- artifactId: json-path-api
  source:
    version: 2.9.0-58.v62e3e85b_a_655
- artifactId: junit
  source:
    version: 1265.v65b_14fa_f12f0
- artifactId: ldap
  source:
    version: 725.v3cb_b_711b_1a_ef
- artifactId: mailer
  source:
    version: 472.vf7c289a_4b_420
- artifactId: matrix-auth
  source:
    version: 3.2.2
- artifactId: matrix-project
  source:
    version: 832.va_66e270d2946
- artifactId: metrics
  source:
    version: 4.2.21-451.vd51df8df52ec
- artifactId: mina-sshd-api-common
  source:
    version: 2.12.1-113.v4d3ea_5eb_7f72
- artifactId: mina-sshd-api-core
  source:
    version: 2.12.1-113.v4d3ea_5eb_7f72
- artifactId: okhttp-api
  source:
    version: 4.11.0-172.vda_da_1feeb_c6e
- artifactId: pam-auth
  source:
    version: 1.11
- artifactId: parameterized-trigger
  source:
    version: 806.vf6fff3e28c3e
- artifactId: periodicbackup
  source:
    version: 2.0
- artifactId: pipeline-build-step
  source:
    version: 540.vb_e8849e1a_b_d8
- artifactId: pipeline-github-lib
  source:
    version: 61.v629f2cc41d83
- artifactId: pipeline-graph-analysis
  source:
    version: 216.vfd8b_ece330ca_
- artifactId: pipeline-graph-view
  source:
    version: 287.v3ef017b_780d5
- artifactId: pipeline-groovy-lib
  source:
    version: 710.v4b_94b_077a_808
- artifactId: pipeline-input-step
  source:
    version: 495.ve9c153f6067b_
- artifactId: pipeline-milestone-step
  source:
    version: 119.vdfdc43fc3b_9a_
- artifactId: pipeline-model-api
  source:
    version: 2.2198.v41dd8ef6dd56
- artifactId: pipeline-model-definition
  source:
    version: 2.2198.v41dd8ef6dd56
- artifactId: pipeline-model-extensions
  source:
    version: 2.2198.v41dd8ef6dd56
- artifactId: pipeline-rest-api
  source:
    version: 2.34
- artifactId: pipeline-stage-step
  source:
    version: 312.v8cd10304c27a_
- artifactId: pipeline-stage-tags-metadata
  source:
    version: 2.2198.v41dd8ef6dd56
- artifactId: pipeline-stage-view
  source:
    version: 2.34
- artifactId: pipeline-utility-steps
  source:
    version: 2.16.2
- artifactId: plain-credentials
  source:
    version: 182.v468b_97b_9dcb_8
- artifactId: plugin-util-api
  source:
    version: 4.1.0
- artifactId: prism-api
  source:
    version: 1.29.0-15
- artifactId: pubsub-light
  source:
    version: 1.18
- artifactId: resource-disposer
  source:
    version: 0.23
- artifactId: scm-api
  source:
    version: 690.vfc8b_54395023
- artifactId: script-security
  source:
    version: 1341.va_2819b_414686
- artifactId: slack
  source:
    version: 722.vd07f1ea_7ff40
- artifactId: snakeyaml-api
  source:
    version: 2.2-111.vc6598e30cc65
- artifactId: sse-gateway
  source:
    version: 1.27
- artifactId: ssh-agent
  source:
    version: 367.vf9076cd4ee21
- artifactId: ssh-credentials
  source:
    version: 337.v395d2403ccd4
- artifactId: ssh-slaves
  source:
    version: 2.968.v6f8823c91de4
- artifactId: sshd
  source:
    version: 3.330.vc866a_8389b_58
- artifactId: structs
  source:
    version: 337.v1b_04ea_4df7c8
- artifactId: theme-manager
  source:
    version: 262.vc57ee4a_eda_5d
- artifactId: thinBackup
  source:
    version: 2.0
- artifactId: timestamper
  source:
    version: 1.27
- artifactId: token-macro
  source:
    version: 400.v35420b_922dcb_
- artifactId: trilead-api
  source:
    version: 2.147.vb_73cc728a_32e
- artifactId: uno-choice
  source:
    version: 2.8.3
- artifactId: variant
  source:
    version: 60.v7290fc0eb_b_cd
- artifactId: workflow-aggregator
  source:
    version: 596.v8c21c963d92d
- artifactId: workflow-api
  source:
    version: 1316.v33eb_726c50b_a_
- artifactId: workflow-basic-steps
  source:
    version: 1058.vcb_fc1e3a_21a_9
- artifactId: workflow-cps
  source:
    version: 3894.3896.vca_2c931e7935
- artifactId: workflow-durable-task-step
  source:
    version: 1353.v1891a_b_01da_18
- artifactId: workflow-job
  source:
    version: 1400.v7fd111b_ec82f
- artifactId: workflow-multibranch
  source:
    version: 783.va_6eb_ef636fb_d
- artifactId: workflow-scm-step
  source:
    version: 427.v4ca_6512e7df1
- artifactId: workflow-step-api
  source:
    version: 657.v03b_e8115821b_
- artifactId: workflow-support
  source:
    version: 907.v6713a_ed8a_573
- artifactId: ws-cleanup
  source:
