services:
  proxy:
    #image: ubuntu/squid:edge
    build: ./edge
    container_name: proxy
    hostname: proxy
    networks:
      - zzizily
    ports:
      - 3128:3128
    environment:
      - TZ=Asia/Seoul
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  zzizily:
    external: true
