services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    hostname: uptime
    restart: unless-stopped
    networks:
      - ice-ops-alm
    ports:
      - 9009:3001
    extra_hosts:
      - dev-m.knou.ac.kr:203.232.174.175
      - dev-m-api.knou.ac.kr:203.232.174.175
      - ci.knou.ac.kr:203.232.174.175
      - regi.knou.ac.kr:203.232.174.175
      - repo.knou.ac.kr:203.232.174.175
      - vcs.knou.ac.kr:203.232.174.175
      - m-config.knou.ac.kr:192.168.10.77
    logging:
      options:
        max-size: 10m
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/app/data
networks:
  ice-ops-alm:
    external: true
volumes:
  data: null
